<VirtualHost *:80>
	ServerName edarl.in
	ServerAlias www.edarl.in
	ServerAdmin webmaster@affinitas.de

    DocumentRoot /var/www/affinitas.de

    #  RewriteLog  NOT FOR PRODUCTION USE !!!
    #--------------------------------------
    #RewriteLogLevel        7
    #RewriteLog             /tmp/rewrite_edarl.in.log

    <IfModule mod_rewrite.c>
        RewriteEngine   On

        # LIITA-8485
        RewriteCond    %{REQUEST_URI}   ^/amor
        RewriteRule    (.*)             http://ad.doubleclick.net/clk;267426381;93232435;j?http://pareja.edarling.es/sys9e2/323340/?CID=ES_DIS_3082279_1383144_93232435_0         [R=permanent,L,NE]

        # AIS-800
        RewriteCond    %{REQUEST_URI}   ^/grupazo
        RewriteRule    (.*)             http://pareja.edarling.es/r127sd/210280/?CID=ES_DIS_3082279_1422653_101001444_0&v=4152ee6c                                                [R=permanent,L,NE]

        # AIS-469
        RewriteCond    %{REQUEST_URI}   ^/vale
        RewriteRule    (.*)             http://www.edarling.es/soltero/vale                                                                                                       [R=permanent,L,NE]

        RewriteCond    %{REQUEST_URI}   ^/tqm
        RewriteRule    (.*)             http://ad.doubleclick.net/clk;267593754;93386524;b?http://pareja.edarling.es/sys9e2/323340/?CID=ES_DIS_3082279_1383144_93386524_0         [R=permanent,L,NE]

        # DRU-1427
        RewriteCond    %{REQUEST_URI}   ^/dooplan
        RewriteRule    (.*)             http://pareja.edarling.es/r127sd/210280/?CID=ES_DIS_3082279_1422653_97005061_0                                                            [R=permanent,L,NE]

        # AIS-646
        RewriteCond    %{REQUEST_URI}   ^/cupon
        RewriteRule    (.*)             http://ad-emea.doubleclick.net/clk;272197613;97988131;x?http://pareja.edarling.es/r127sd/210280/?CID=ES_DIS_3082279_1139257_97988131_%ecid!_ELI1!   [R=permanent,L,NE]

        RewriteCond    %{REQUEST_URI}   ^/ticket
        RewriteRule    (.*)             http://ad-emea.doubleclick.net/clk;272196958;97987236;n?http://pareja.edarling.es/r127sd/210280/?CID=ES_DIS_3082279_1139257_97987236_%ecid!_ELI2!   [R=permanent,L,NE]

        # AIS-1381
        RewriteCond    %{REQUEST_URI}   ^/corazon
        RewriteRule    (.*)             http://ad.doubleclick.net/ddm/clk/280764074;107605194;g                                                                                             [R=permanent,L,NE]

        # AIS-1400
        RewriteCond    %{REQUEST_URI}   ^/vpDE
        RewriteRule    (.*)             http://ad.doubleclick.net/ddm/clk/280895435;107703982;q                                                                                             [R=permanent,L,NE]

        RewriteCond    %{REQUEST_URI}   ^/vpFR
        RewriteRule    (.*)             http://ad.doubleclick.net/ddm/clk/280898806;107705571;r                                                                                             [R=permanent,L,NE]

        RewriteCond    %{REQUEST_URI}   ^/vpES
        RewriteRule    (.*)             http://ad.doubleclick.net/ddm/clk/280899249;107703945;w                                                                                             [R=permanent,L,NE]

        # general/default rewrite
        RewriteRule    (.*)             http://edarling.es  [R=302,L]
    </IfModule>

	ErrorLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/edarl.in.error_log.%Y-%m-%d.log 86400"

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/edarl.in.access_log.%Y-%m-%d.log 86400" combined

</VirtualHost>
# ex: set syntax=apache tabstop=2 expandtab:
