<VirtualHost *:80>
	ServerName elittars.hu
    ServerAlias tarskereso.elittars.hu
	ServerAdmin webmaster@localhost

	DocumentRoot /var/www/tarskereso.elittars.hu
    
    #Include includes/block_ip
    Include includes/all

	ErrorLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/tarskereso.elittars.hu.error_log.%Y-%m-%d.log 86400"

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/tarskereso.elittars.hu.access_log.%Y-%m-%d.log 86400" combined
</VirtualHost>
