<VirtualHost *:80>
	ServerName  affinitas.de
	ServerAlias www.affinitas.de
	ServerAdmin webmaster@localhost

    <IfModule mod_rewrite.c>
        RewriteEngine       On

        RewriteCond  %{REQUEST_URI}     ^/career$
        RewriteRule  (.*)               https://www.spark.net/careers/     [R=permanent,L]

        RedirectMatch 301 ^(.*)$        https://www.spark.net/
    </IfModule>


	DocumentRoot /var/www/affinitas.de/current
    

	<Directory />
		Options FollowSymLinks
		AllowOverride None
	</Directory>
	<Directory /var/www/affinitas.de/current>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride None
		Order allow,deny
		allow from all
	</Directory>

	ErrorLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/www.affinitas.de.error_log.%Y-%m-%d.log 86400"

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/www.affinitas.de.access_log.%Y-%m-%d.log 86400" combined
</VirtualHost>
