version: '3.5'

services:

# Linked Admin
  admin:
    image: buoyantio/linkerd:1.3.5
    domainname: ellesmera.org
    ulimits:
      memlock:
        soft: -1
        hard: -1

    deploy:
        replicas: 1
        update_config:
            parallelism: 2
            delay: 10s
        restart_policy:
            condition: on-failure
        endpoint_mode: vip
        labels:
            com.example.description: "POC"

        resources:
            limits:
                cpus: '0.50'
                memory: 1G
            reservations:
                cpus: '0.25'
                memory: 800M
    volumes:
      - ./config/config.yaml:/config.yaml

    ports:
      - 9090:9090
      - 8080:8080

    networks:
      - docker2docker

networks:

    docker2docker:
        external: true
