global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'master'


# A list of scrape configurations.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout:  10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'mysql:9104'
        labels:
          group: 'mysql group servers' 
          alias: 'mysql 5.7'
          

  - job_name: 'postgresql'
    scrape_interval: 20s
    static_configs:
      - targets:
        - 'postgres:5432'
        labels:
          group: 'postgresql group servers'
          alias: 'postgresql 6.4'