cluster.name: "docker-cluster"
network.host: 0.0.0.0

# Node names are generated dynamically on startup, so you're relieved
# from configuring them manually. You can tie this node to a specific name:
node.name: "{{HOSTNAME}}"

# Allow this node to be eligible as a master node (enabled by default):
node.master: true

bootstrap.memory_lock: true
action.auto_create_index: true

# Set the number of shards (splits) of an index (5 by default):
index.number_of_shards: 2

# Set the number of replicas (additional copies) of an index (1 by default):
index.number_of_replicas: 1

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.license.self_generated.type: basic
xpack.monitoring.collection.indices: servers-*, databases-*, docker-*, elasticsearch-*, metricbeat-*
