version: '3.5'

services:

  traefik:
    image: traefik 
    environment:
      HOSTNAME: traefik
      SERVICE_NAME: traefik
      SERVICE_TAGS: lb, proxy
    command: --api --file --file.watch --docker --docker.watch
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    ports:
      - target: 80
        published: 80
        mode: host     
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/traefik/
    networks:
      - docker2docker
  
networks:
    docker2docker:
        external: true