# Frontend definition
[frontends]

  [frontends.admin2]
  backend = "admin2"
  passHostHeader = true
  passTLSCert = true
  priority = 10
    [frontends.admin2.routes.admin2]
      rule = "Host:admin2.ellesmera.com,Host:whoami.ellesmera.com,Host:portal2.ellesmera.com"


# Backend definition
[backends]

  [backends.admin2]
    [backends.admin2.LoadBalancer]
    sticky = false
    method = "wrr"
    [backends.admin2.servers.server1]
    url = "http://admin2"
    weight = 10
    [backends.admin2.servers.server2]
    url = "http://whoami"
    weight = 8
    [backends.admin2.servers.server3]
    url = "http://portal2"
    weight = 6
  frontEndRule = "Host:{{.ServiceName}}.{{.Domain}}"