################################################################
# Global configuration
################################################################

# Enable debug mode
debug = true


# Log level
logLevel = "DEBUG"

# Entrypoints to be used by frontends that do not specify any entrypoint.
defaultEntryPoints = ["http"]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
[entryPoints]
   [entryPoints.http]
   address = ":80"
   compress = true

[file]
filename = "/etc/traefik/traefik.toml"
watch = true
  
################################################################
# Traefik logs configuration
################################################################

# Traefik logs
[traefikLog]
  filePath = "log/traefik.log"
  format = "common"

################################################################
# Access logs configuration
################################################################

# Enable access logs
[accessLog]
  # filePath = "/path/to/log/log.txt"
  format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Name of the related entry point
  entryPoint = "traefik"

  # Enabled Dashboard
  dashboard = true

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

  watch = true

  swarmmode = true

  # endpoint = "tcp://10.10.10.10:2375"
  endpoint = "unix:///var/run/docker.sock"

  domain = "ellesmera.com"

  exposedbydefault = true

################################################################
# Consul Catalog configuration backend
################################################################

# Enable Consul Catalog configuration backend.
[consulCatalog]

  watch = false
  
  endpoint = "consul_server:8500"

  exposedByDefault = false

  domain = "ellesmera.com"

  prefix = "traefik"

#   # Default frontEnd Rule for Consul services.
#   #
#   # The format is a Go Template with:
#   # - ".ServiceName", ".Domain" and ".Attributes" available
#   # - "getTag(name, tags, defaultValue)", "hasTag(name, tags)" and "getAttribute(name, tags, defaultValue)" functions are available
#   # - "getAttribute(...)" function uses prefixed tag names based on "prefix" value
#   #
#   # Optional
#   # Default: "Host:{{.ServiceName}}.{{.Domain}}"
#   #
  frontEndRule = "Host:{{.ServiceName}}.{{.Domain}}"

[metrics]

  watch = true
  
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]

  buckets=[0.1,0.3,1.2,5.0]

############################# Custom settings ###################################


# Backend definition
[backends]

  [backends.backend1]
    [backends.backend1.LoadBalancer]
    method = "drr"
    [backends.backend1.servers.new]
    url = "http://portal2"
    weight = 5
    [backends.backend1.servers.legacy]
    url = "http://portal1"
    weight = 3

# Frontend definition
[frontends]

  [frontends.portal2]
  backend = "backend1"
  FrameDeny = true
  passHostHeader = true
  passTLSCert = true
  priority = 10
    [frontends.portal2.routes.portal2]
      rule = "HostRegexp:ellesmera.com,{subdomain:[a-z][0-9]+}.ellesmera.com"
