################################################################
# Global configuration
################################################################

# Entrypoints to be used by frontends that do not specify any entrypoint.
defaultEntryPoints = ["http"]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
[entryPoints]
   [entryPoints.http]
   address = ":80"
   compress = true
  
################################################################
# Traefik logs configuration
################################################################

# Traefik logs
[traefikLog]
  filePath = "log/traefik.log"
  format = "common"

################################################################
# Access logs configuration
################################################################

# Enable access logs
[accessLog]
  # filePath = "/path/to/log/log.txt"
  format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Name of the related entry point
  entryPoint = "traefik"

  # Enabled Dashboard
  dashboard = true

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

  watch = true

  swarmmode = true

  # endpoint = "tcp://10.10.10.10:2375"
  endpoint = "unix:///var/run/docker.sock"

  domain = "ellesmera.com"

  exposedbydefault = true

################################################################
# Consul Catalog configuration backend
################################################################

# Enable Consul Catalog configuration backend.
[consulCatalog]

  watch = false
  
  endpoint = "consul_server:8500"

  exposedByDefault = false

  domain = "ellesmera.com"

  prefix = "traefik"

  frontEndRule = "Host:{{.ServiceName}}.{{.Domain}}"

[metrics]

  watch = true
  
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]
  buckets=[0.1,0.3,1.2,5.0]

[file]
watch = true

############################# Custom settings ###################################

# Frontend definition
[frontends]

  [frontends.portal2]
  backend = "portal2"
  FrameDeny = true
  passHostHeader = true
  passTLSCert = true
  priority = 10
    [frontends.portal2.routes.portal2]
        rule = "HostRegexp: ellesmera.com,portal([0-9])+.ellesmera.com"
    [frontends.portal2.errors]
        [frontends.portal2.errors.errorPage0]
        status = ["500-599"]
        backend = "error"
        query = "/{status}.html"
        [frontends.portal2.errors.errorPage1]
        status = ["404", "403"]
        backend = "error"
        query = "/{status}.html"
        # ...

    [frontends.portal2.ratelimit]
        extractorfunc = "client.ip"
        [frontends.portal2.ratelimit.rateset.rateset1]
            period = "10s"
            average = 100
            burst = 200
        [frontends.portal2.ratelimit.rateset.rateset2]
            period = "3s"
            average = 5
            burst = 10

  [frontends.vault]
  backend = "vaultsrv"
  FrameDeny = true
  passHostHeader = true
  passTLSCert = true
  priority = 20
    [frontends.vault.routes.vault_1]
      rule = "Host: vault.ellesmera.com,ellesmera.com"

################# Backend definition #########################
[backends]

  [backends.portal2]
    [backends.portal2.circuitbreaker]
    expression = "NetworkErrorRatio() > 0.5"
    [backends.portal2.maxconn]
       amount = 10
       extractorfunc = "request.host"    
    [backends.portal2.loadbalancer.stickiness]
        cookiename = "portal2_cookie"
    [backends.portal2.healthcheck]
    path = "/health"
    interval = "10s"    
    [backends.portal2.LoadBalancer]
    method = "drr"
    [backends.portal2.servers.new]
    url = "http://portal2"
    weight = 5
    [backends.portal2.servers.legacy]
    url = "http://portal1"
    weight = 2

  [backends.vault]
    [backends.vault.circuitbreaker]
    expression = "NetworkErrorRatio() > 0.5"
    [backends.vault.maxconn]
       amount = 10
       extractorfunc = "request.host"    
    [backends.vault.loadbalancer.stickiness]
        cookiename = "vault_cookie"
    [backends.vault.healthcheck]
    path = "/health"
    interval = "10s"    
    [backends.vault.LoadBalancer]
    method = "drr"
    [backends.vault.servers.new]
    url = "http://vault_server"
    weight = 5