################################################################
# Global configuration
################################################################

# Entrypoints to be used by frontends that do not specify any entrypoint.
defaultEntryPoints = ["http"]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
[entryPoints]
   [entryPoints.http]
   address = ":80"
   compress = true
  
################################################################
# Traefik logs configuration
################################################################

# Traefik logs
[traefikLog]
  filePath = "log/traefik.log"
  format = "common"

################################################################
# Access logs configuration
################################################################

# Enable access logs
[accessLog]
  # filePath = "/path/to/log/log.txt"
  format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Name of the related entry point
  entryPoint = "traefik"

  # Enabled Dashboard
  dashboard = true

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

  watch = true

  swarmmode = true

  # endpoint = "tcp://10.10.10.10:2375"
  endpoint = "unix:///var/run/docker.sock"

  domain = "ellesmera.com"

  exposedbydefault = false

################################################################
# Consul Catalog configuration backend
################################################################

# Enable Consul Catalog configuration backend.
[consulCatalog]

  watch = true
  
  endpoint = "consul_server:8500"

  exposedByDefault = true

  domain = "ellesmera.com"

  prefix = "traefik"

  # frontEndRule = "Host:{{.Tags}}.{{.Domain}}"
  frontEndRule = "Host:{{.ServiceName}}.{{.Domain}}"
  # frontEndRule = "Host:{{getTag  .ServiceName }}"
[metrics]

  watch = true
  
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]
  buckets=[0.1,0.3,1.2,5.0]

# [file]
# watch = false
# directory = "/rules"
  
[retry]