<VirtualHost *:80>
	ServerName celibataire.nosbellesannees.fr
	ServerAdmin webmaster@localhost

	DocumentRoot /var/www/celibataire.nosbellesannees.fr

  Include includes/all

	ErrorLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/celibataire.nosbellesannees.fr.error_log.%Y-%m-%d.log 86400"

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/celibataire.nosbellesannees.fr.access_log.%Y-%m-%d.log 86400" combined
</VirtualHost>
