<VirtualHost *:80>
	ServerName dating.ldssingles.com
	ServerAdmin webmaster@localhost

	DocumentRoot /var/www/dating.ldssingles.com

  Include includes/all

	ErrorLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/dating.ldssingles.com.error_log.%Y-%m-%d.log 86400"

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/dating.ldssingles.com.access_log.%Y-%m-%d.log 86400" combined
</VirtualHost>
