<VirtualHost *:80>
	ServerName partner.silbersingles.de
	ServerAdmin webmaster@localhost

	DocumentRoot /var/www/partner.silbersingles.de

  Include includes/all

	ErrorLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/partner.silbersingles.de.error_log.%Y-%m-%d.log 86400"

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog "|/usr/sbin/rotatelogs ${APACHE_LOG_DIR}/partner.silbersingles.de.access_log.%Y-%m-%d.log 86400" combined
</VirtualHost>
