version: '3'

services:

  db:
    image: mysql:5.7
    hostname: db
    volumes:
      - /opt/data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
      ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - stack

  wordpress:
    image: tutum/wordpress
    hostname: wordpress
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - stack

  nginx:
    image: nginx:1.12
    hostname: nginx
    ports:
      - "81:80"
      - "8000:80/tcp"
    networks:
      - stack

  haproxy:
    image: haproxy:1.6
    hostname: haproxy
    environment:
      HAPROXY_CFG: "/etc/haproxy/haproxy.cfg"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      replicas: 1
      placement:
        constraints:
           - node.role == manager
    ports:
      - "80:80"
    networks:
      - stack

volumes:
    db_data:

networks:
  stack:
    driver: overlay
