version: '3'

services:

  haproxy:
    image: haproxy:1.6
    hostname: haproxy
    environment:
      HAPROXY_CFG: "/etc/haproxy/haproxy.cfg"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      replicas: 1
      placement:
        constraints:
           - node.role == manager
    ports:
      - "8008:80"
    networks:
      - docker2docker

networks:
  docker2docker:
    external: true
