version: '3.7'

services:

  portal1:
    image: jwilder/whoami
    environment:
      SERVICE_NAME: portal1
      SERVICE_TAGS: blue
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portal1.service=portal1"
        - "traefik.http.routers.portal1.entrypoints=web,websecure"
        - "traefik.http.routers.portal1.rule=Host(`portal.ellesmera`)"
        - "traefik.http.services.portal1.loadbalancer.sticky=true"
        - "traefik.http.services.portal1.loadbalancer.server.port=8000"
        - "traefik.http.services.portal1.loadbalancer.server.scheme=http"
        - "traefik.http.services.portal1.loadbalancer.sticky.cookie.name=portal1"
        - "traefik.http.services.portal1.loadbalancer.passhostheader=true"
      replicas: 2
      endpoint_mode: dnsrr
    expose:
      - "8000"
    networks:
      - docker2docker
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  portal2:
    image: jwilder/whoami
    environment:
      SERVICE_NAME: portal2
      SERVICE_TAGS: green
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portal2.service=portal2"
        - "traefik.http.routers.portal2.entrypoints=web,websecure"
        - "traefik.http.routers.portal2.rule=Host(`portal.ellesmera`)"
        - "traefik.http.services.portal2.loadbalancer.sticky=true"
        - "traefik.http.services.portal2.loadbalancer.server.port=8000"
        - "traefik.http.services.portal2.loadbalancer.server.scheme=http"
        - "traefik.http.services.portal2.loadbalancer.sticky.cookie.name=portal2"
        - "traefik.http.services.portal2.loadbalancer.passhostheader=true"
      replicas: 2
      endpoint_mode: dnsrr
    expose:
      - "8000"
    networks:
      - docker2docker
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  docker2docker:
    external: true