version: '3.5'

services:

  portal1:
    image: jwilder/whoami
    environment:
      SERVICE_NAME: portal1
      SERVICE_TAGS: traefik.enable=true,traefik.frontend.rule=Host:portal1.ellesmera.com
    labels:
      - "traefik.backend=ellesmera.com"
      - "traefik.frontend.rule=Host:portal.ellesmera.com"      
    deploy:
      replicas: 1
    networks:
      - docker2docker
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://logstash:12201
    #     tag: "staging"
    volumes:
      - ./html/1/index.html:/usr/share/nginx/html/index.html

  portal2:
    image: jwilder/whoami
    environment:
      SERVICE_NAME: portal2
      SERVICE_TAGS: traefik.enable=true,traefik.frontend.rule=Host:portal2.ellesmera.com
    labels:
      - "traefik.backend=ellesmera.com"
      - "traefik.frontend.rule=Host:portal.ellesmera.com"
    volumes:
      - ./html/2/index.html:/usr/share/nginx/html/index.html
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://logstash:12201
    #     tag: "staging"
    deploy:
      replicas: 1
    networks:
      - docker2docker

networks:
  docker2docker:
    external: true