version: '3.6'

services:

  portal1:
    image: jwilder/whoami
    environment:
      SERVICE_NAME: portal1
      SERVICE_TAGS: blue
    labels:
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.weight=30"
      - "traefik.backend=portal2"
      - "traefik.tags=blue"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.frontend.rule=Host:portal.ellesmera.com"
      - "traefik.backend.loadbalancer.stickiness.cookieName=blue_cookie"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    networks:
      - docker2docker
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  portal2:
    image: jwilder/whoami
    environment:
      SERVICE_NAME: portal2
      SERVICE_TAGS: green
    labels:
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.backend=portal2"
      - "traefik.tags=green"
      - "traefik.weight=20"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.frontend.rule=Host:portal.ellesmera.com"
      - "traefik.backend.loadbalancer.stickiness.cookieName=green_cookie"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    networks:
      - docker2docker

networks:
  docker2docker:
    external: true