version: '3.6'

services:

  server:
    image: vault:0.10.0
    privileged: true
    working_dir: /vault/config/
    environment:
      VAULT_ADDR: http://vault_server:8200
      VAULT_ROOT_TOKEN_ID: protectme
      SERVICE_NAME: vault
      SERVICE_TAGS: vault, seal, encrypt
    labels:
      - "traefik.backend=vault"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.backend.loadbalancer.stickiness.cookieName=vault"
      - "traefik.frontend.rule=Host:vault.ellesmera.com"        
    volumes:
      - ./config/:/vault/config/:rw
    command: vault server -config /vault/config/ -log-level=debug
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1G  
    networks:
      - docker2docker
      
networks:
    docker2docker:
        external: true