version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    hostname: elasticsearch
    domainname: ellesmera.org
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
      http.host: "0.0.0.0"
      cluster.name: "docker-cluster"
      node.name: ${HOSTNAME}
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.0.0
    hostname: logstash
    domainname: ellesmera.org
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /var/log/messages:/tmp/messages
    command: "logstash -f /usr/share/logstash/config/logstash.conf"
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch:elasticsearch

  kibana:
    image:  docker.elastic.co/kibana/kibana:6.0.0
    hostname: kibana
    domainname: ellesmera.org
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch:elasticsearch

  beats:
    image:  docker.elastic.co/beats/filebeat:6.0.0
    hostname: filebeats
    domainname: ellesmera.org
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    networks:
      - elk
    depends_on:
      - elasticsearch:elasticsearch
      - kibana:kibana

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  elk:
    driver: overlay
