version: '3.6'

services:
  portainer:
    image: portainer/portainer
    environment:
      SERVICE_NAME: portainer
      SERVICE_TAG: ui, management
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - docker2docker
      
networks:
  docker2docker:
    external: true

volumes:
  portainer_data: