version: '3.5'

volumes:
  consul:

services:
  consul:
    image: consul:latest
    command: -server
    volumes:
      - consul:/consul/data
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 126M
      restart_policy:
        condition: any
        delay: 5s
    ports:
        - 8500:8500

  registrator:
    image: gliderlabs/registrator:latest
    command: -resync 30 -internal consul://consul:8500
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - docker2docker
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
    docker2docker:
        external: true
    host:
        external: true